import {useEffect,useMemo,useRef,useState} from "react";
import {Camera,CheckCircle2,Copy,HeartHandshake,Inbox,Pencil,Pause,Play,Plus,Share2,Trash2,X} from "lucide-react";
import {Link} from "react-router-dom";
import {addMyOpportunity,deleteMyOpportunity,loadIncomingRequests,loadMyPassport,opportunityGroups,respondToPassportRequest,saveMyPassport,setMyOpportunityActive,updateMyOpportunity,uploadOpportunityPhoto} from "../services/passportStore";
const durations=[{value:"hour",label:"1 година"},{value:"day",label:"1 день"},{value:"month",label:"1 місяць"},{value:"year",label:"1 рік"}];
const paymentOptions=[{value:"free",label:"Безкоштовно"},{value:"paid",label:"За оплату"},{value:"exchange",label:"Обмін"},{value:"negotiable",label:"За домовленістю"}];
const priceUnits=["кг","шт.","година","консультація","послуга","день","поїздка","комплект"];const currencySymbols={UAH:"грн",USD:"$",EUR:"€"};
const emptyEntry=()=>({group:"have",text:"",duration:"month",place:"",radiusValue:"",radiusUnit:"км",online:false,paymentType:"free",priceValue:"",priceUnit:"шт.",currency:"UAH",minimumQuantity:"",deliveryIncluded:false,photoUrl:"",photoLabel:"",photoTask:""});
function friendlyError(error){const text=String(error?.message||error||"");if(/anonymous|signups|disabled/i.test(text))return "У Supabase потрібно увімкнути анонімний вхід.";if(/atlas_requests|relation .*atlas_requests.*does not exist/i.test(text))return "Запити між користувачами ще не активовані.";if(/atlas_passports|atlas_opportunities|atlas_private_contacts|atlas_needs|relation .* does not exist/i.test(text))return "База Паспортів ще не активована.";return text||"Не вдалося виконати дію."}
function cleanRequestMessage(value){return String(value||"").replace(/[\u200B-\u200D\u2060\u2062\u2063\uFEFF]*ATLAS_META:[^\r\n]*/gu,"").replace(/\n{3,}/g,"\n\n").trim()}
function OpportunityFields({value,onChange,textareaRef,compact=false,onPhoto}){const paid=value.paymentType==="paid";const photo=value.photoUrl||value.photo_url;return <div className="opportunityFields">
<label><span>Підгрупа</span><select value={value.group} onChange={e=>onChange({...value,group:e.target.value})}>{opportunityGroups.map(g=><option key={g.value} value={g.value}>{g.label}</option>)}</select></label>
<label><span>Можливість</span><textarea ref={textareaRef} required maxLength={1100} value={value.text} onChange={e=>onChange({...value,text:e.target.value})} placeholder="Наприклад: маю велосипед, можу продати" style={{minHeight:compact?72:82}}/></label>
{!compact&&<div className="opportunityPhotoField">{photo?<div className="opportunityPhotoPreview"><img src={photo} alt="Фото можливості"/><span>{value.photoLabel||value.photo_label||"Фото додано"}</span><button type="button" onClick={()=>onChange({...value,photoUrl:"",photoLabel:"",photoTask:""})}><X size={16}/></button></div>:<label className="opportunityPhotoButton"><Camera size={19}/><span>Додати фото</span><input type="file" accept="image/*" capture="environment" onChange={onPhoto}/></label>}<small>Сфотографуйте річ. Після активації AI Atlas зможе визначати її та знаходити схожі.</small></div>}
<fieldset className="durationPicker"><legend>Актуальність</legend><div>{durations.map(i=><button type="button" className={value.duration===i.value?"active":""} key={i.value} onClick={()=>onChange({...value,duration:i.value})}>{i.label}</button>)}</div></fieldset>
<label><span>Умови надання</span><select value={value.paymentType} onChange={e=>onChange({...value,paymentType:e.target.value})}>{paymentOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>
{paid&&<div className="opportunityPrice"><label><span>Ціна</span><input required inputMode="decimal" value={value.priceValue} onChange={e=>onChange({...value,priceValue:e.target.value.replace(/[^0-9.,]/g,"").slice(0,14)})}/></label><label><span>Одиниця</span><select value={value.priceUnit} onChange={e=>onChange({...value,priceUnit:e.target.value})}>{priceUnits.map(u=><option key={u}>{u}</option>)}</select></label><label><span>Валюта</span><select value={value.currency} onChange={e=>onChange({...value,currency:e.target.value})}><option value="UAH">грн</option><option value="USD">USD</option><option value="EUR">EUR</option></select></label></div>}
<div className="opportunityLocation"><label><span>Місце</span><input value={value.place} onChange={e=>onChange({...value,place:e.target.value})}/></label><label><span>Радіус</span><input inputMode="decimal" value={value.radiusValue} onChange={e=>onChange({...value,radiusValue:e.target.value.replace(/[^0-9.,]/g,"")})}/></label></div></div>}
function opportunityMeta(item){return [paymentOptions.find(o=>o.value===item.paymentType)?.label,item.paymentType==="paid"&&item.priceValue?`${item.priceValue} ${currencySymbols[item.currency]||item.currency} / ${item.priceUnit}`:"",durations.find(o=>o.value===item.duration)?.label,item.place].filter(Boolean)}
export default function Profile(){const addRef=useRef(null),textareaRef=useRef(null);const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[adding,setAdding]=useState(false),[photoBusy,setPhotoBusy]=useState(false),[busyId,setBusyId]=useState(""),[editing,setEditing]=useState(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[passport,setPassport]=useState(null),[opportunities,setOpportunities]=useState([]),[requests,setRequests]=useState([]),[form,setForm]=useState({displayName:"",city:"",contact:"",profession:"",skills:""}),[entry,setEntry]=useState(emptyEntry);
const shareUrl=useMemo(()=>passport?.slug?`${window.location.origin}/p/${passport.slug}`:"",[passport?.slug]);const activeCount=opportunities.filter(i=>i.is_active).length;const pendingRequests=useMemo(()=>requests.filter(i=>i.status==="pending"),[requests]);
useEffect(()=>{let alive=true;loadMyPassport().then(async d=>{if(!alive)return;setPassport(d.passport);setOpportunities(d.opportunities||[]);setForm({displayName:d.passport?.display_name||"",city:d.passport?.city||"",contact:d.contact||"",profession:d.passport?.profession||"",skills:d.passport?.skills||""});if(d.passport?.id){try{setRequests(await loadIncomingRequests())}catch{}}}).catch(e=>alive&&setError(friendlyError(e))).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[]);
function scrollToAdd(){setEditing(null);addRef.current?.scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>textareaRef.current?.focus(),320)}
async function savePassport(e){e.preventDefault();setSaving(true);try{const s=await saveMyPassport(form);setPassport(s);setNotice("Паспорт збережено.")}catch(c){setError(friendlyError(c))}finally{setSaving(false)}}
async function addPhoto(e){const file=e.target.files?.[0];if(!file)return;setPhotoBusy(true);setError("");try{const uploaded=await uploadOpportunityPhoto(file);let label="";try{const reader=new FileReader();const image=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const r=await fetch("/api/vision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image,lang:"uk"})});const data=await r.json();if(r.ok)label=data.name||""}catch{}setEntry(v=>({...v,photoUrl:uploaded.url,photoLabel:label,photoTask:label?`Знайти схоже: ${label}`:""}));setNotice(label?`Фото додано · ${label}`:"Фото додано. Розпізнавання запрацює після активації AI.")}catch(c){setError(friendlyError(c))}finally{setPhotoBusy(false)}}
async function addOpportunity(e){e.preventDefault();if(adding||photoBusy||!passport?.id||!entry.text.trim())return;setAdding(true);try{const a=await addMyOpportunity(passport.id,entry);setOpportunities(x=>[a,...x]);setEntry(v=>({...emptyEntry(),group:v.group}));setNotice("Можливість додано.")}catch(c){setError(friendlyError(c))}finally{setAdding(false)}}
async function toggleOpportunity(i){setBusyId(i.id);try{const u=await setMyOpportunityActive(i.id,!i.is_active);setOpportunities(x=>x.map(v=>v.id===u.id?u:v))}finally{setBusyId("")}}
async function removeOpportunity(id){if(!confirm("Видалити цю можливість?"))return;setBusyId(id);try{await deleteMyOpportunity(id);setOpportunities(x=>x.filter(i=>i.id!==id))}finally{setBusyId("")}}
async function answerRequest(id,status){setBusyId(id);try{const u=await respondToPassportRequest(id,status);setRequests(x=>x.map(i=>i.id===id?{...i,...u}:i))}finally{setBusyId("")}}
async function copyLink(){if(shareUrl){await navigator.clipboard.writeText(shareUrl);setNotice("Посилання скопійовано.")}}async function sharePassport(){if(navigator.share){await navigator.share({title:"Atlas",url:shareUrl}).catch(()=>{});return}await copyLink()}
if(loading)return <main className="page appPage"><section className="profileShell"><p>Відкриваю Паспорт…</p></section></main>;
return <main className="page appPage"><section className="profileShell passportPage"><div className="passportHeading"><div><span className="kicker">ATLAS · ПАСПОРТ МОЖЛИВОСТЕЙ</span><h1>{passport?"Ваш Паспорт":"Створіть Паспорт"}</h1><p>Твої можливості — це частинка чиєїсь задачі.</p></div>{passport&&<div className="passportCounter"><strong>{activeCount}</strong><span>активних</span></div>}</div>
<form className="passportIdentity" onSubmit={savePassport}><label><span>Ім’я або псевдонім</span><input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label><span>Місто / район</span><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label className="contactField"><span>Приватний контакт</span><input required value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label><button className="secondary" disabled={saving}>{saving?"Зберігаю…":passport?"Зберегти":"Створити Паспорт"}</button></form>
{passport&&<><section className="passportActions"><button className="primary" type="button" onClick={scrollToAdd}><Plus size={19}/>Додати можливість</button><Link className="needsShortcut" to="/needs"><HeartHandshake size={18}/>Мої потреби</Link><button className="secondary" type="button" onClick={sharePassport}><Share2 size={17}/>Поділитися</button><button className="secondary iconButton" type="button" onClick={copyLink}><Copy size={17}/></button></section>
<section className="opportunityEditor" ref={addRef}><div className="sectionTitle"><div><span>НОВА МОЖЛИВІСТЬ</span><h2>Додати як є</h2></div></div><form onSubmit={addOpportunity}><OpportunityFields value={entry} onChange={setEntry} textareaRef={textareaRef} onPhoto={addPhoto}/><button className="primary addOpportunity" disabled={adding||photoBusy||!entry.text.trim()}><Plus size={18}/>{photoBusy?"Додаю фото…":adding?"Додаю…":"Додати до Паспортa"}</button></form></section>
<section className="opportunityGroups"><div className="sectionTitle"><div><span>МОЇ МОЖЛИВОСТІ</span><h2>{opportunities.length} записів</h2></div></div>{opportunityGroups.map(g=>{const items=opportunities.filter(i=>i.group===g.value);return <details className="opportunityGroup" key={g.value} open={items.length>0}><summary><span>{g.label}</span><b>{items.length}</b></summary><div className="opportunityList">{items.map(i=><article className={`opportunityCard ${i.is_active?"":"paused"}`} key={i.id}>{i.photo_url&&<img className="opportunityCardPhoto" src={i.photo_url} alt={i.photo_label||i.text}/>}<div className="opportunityCopy"><p>{i.text}</p>{i.photo_label&&<small>{i.photo_label}</small>}<div className="opportunityMeta">{opportunityMeta(i).map(v=><span key={v}>{v}</span>)}</div></div><div className="recordActions"><button type="button" disabled={busyId===i.id} onClick={()=>toggleOpportunity(i)}>{i.is_active?<><Pause size={16}/>Призупинити</>:<><Play size={16}/>Активувати</>}</button><button className="deleteAction" type="button" onClick={()=>removeOpportunity(i.id)}><Trash2 size={16}/>Видалити</button></div></article>)}</div></details>})}</section>
<section className="incomingRequests"><div className="sectionTitle"><h2><Inbox size={21}/>Вхідні{pendingRequests.length?` · ${pendingRequests.length}`:""}</h2></div>{pendingRequests.length===0?<p className="groupEmpty">Нових запитів немає.</p>:pendingRequests.map(i=><article key={i.id}><div><strong>{i.requester_name||"Користувач Atlas"}</strong><p>{cleanRequestMessage(i.message)}</p></div><div><button className="primary" onClick={()=>answerRequest(i.id,"accepted")}><CheckCircle2 size={16}/>Прийняти</button><button className="secondary" onClick={()=>answerRequest(i.id,"declined")}><X size={16}/>Відхилити</button></div></article>)}</section></>}{error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}</section></main>}
