import {useMemo,useState} from "react";
import {Routes,Route,Link,useNavigate,useLocation} from "react-router-dom";
import {Globe2,MapPin,Search,ArrowLeft,CheckCircle2} from "lucide-react";
import {createClient} from "@supabase/supabase-js";

const dict={
uk:{profile:"Профіль можливостей",h1:"У світі майже всі рішення вже існують.",h2:"Потрібно лише правильно поєднати можливості людей.",task:"Що ви хочете вирішити?",taskPh:"Наприклад: потрібно викопати фундамент",where:"Де це потрібно?",wherePh:"Місто, район або область",build:"Побудувати рішення",create:"Створити Профіль можливостей",principle:"Твоя можливість — це частина чиєїсь задачі.",found:"Рішення знайдено",sub:"Atlas побудував найкоротший ланцюг можливостей.",back:"Назад",distance:"Загальна відстань",people:"Учасників",expand:"Розширити пошук",name:"Хто ви?",city:"Де ви?",can:"Що ви можете?",have:"Що у вас є?",share:"Чим можете поділитися?",useful:"У чому можете бути корисними?",need:"Що вам потрібно?",contact:"Контакт",save:"Зберегти профіль",saved:"Профіль збережено"},
en:{profile:"Opportunity Profile",h1:"Almost every solution already exists.",h2:"We only need to connect people's capabilities correctly.",task:"What do you want to solve?",taskPh:"For example: I need to excavate a foundation",where:"Where is it needed?",wherePh:"City, district or region",build:"Build a solution",create:"Create Opportunity Profile",principle:"Your capability is part of someone else's task.",found:"Solution found",sub:"Atlas built the shortest chain of capabilities.",back:"Back",distance:"Total distance",people:"Participants",expand:"Expand search",name:"Who are you?",city:"Where are you?",can:"What can you do?",have:"What do you have?",share:"What can you share?",useful:"How can you be useful?",need:"What do you need?",contact:"Contact",save:"Save profile",saved:"Profile saved"}};

const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;

function Header({lang,setLang,t}){return <header><Link className="brand" to="/"><b>A</b><span>ATLAS</span></Link><div className="actions"><Link to="/profile">{t.profile}</Link><button className="lang" onClick={()=>setLang(lang==="uk"?"en":"uk")}><Globe2 size={17}/>{lang==="uk"?"UA":"EN"}</button></div></header>}

function Home({t}){const [task,setTask]=useState("");const [where,setWhere]=useState("");const nav=useNavigate();function go(e){e.preventDefault();if(task.trim())nav("/solution",{state:{task,where}})}return <main className="home"><section className="hero"><h1>{t.h1}<span>{t.h2}</span></h1><form className="searchbox" onSubmit={go}><label>{t.task}</label><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder={t.taskPh}/><label>{t.where}</label><div className="location"><MapPin size={20}/><input value={where} onChange={e=>setWhere(e.target.value)} placeholder={t.wherePh}/></div><button className="primary"><Search size={20}/>{t.build}</button></form><Link className="profileLink" to="/profile">{t.create}</Link><p className="principle">{t.principle}</p></section></main>}

function Solution({t}){const {state}=useLocation();const items=[["Іван К.","Може копати","3 км"],["Петро М.","Має екскаватор","7 км"],["Андрій С.","Перевозить матеріали","5 км"]];return <main className="page"><div className="shell"><Link className="back" to="/"><ArrowLeft size={18}/>{t.back}</Link><div className="title"><div className="ok"><CheckCircle2/></div><div><h1>{t.found}</h1><p>{t.sub}</p></div></div><div className="query"><strong>{state?.task||"Потрібно виконати задачу"}</strong><span><MapPin size={16}/>{state?.where||"Локація не вказана"}</span></div><div className="grid"><section className="chain">{items.map((x,i)=><article key={i}><div className="num">{i+1}</div><div className="avatar">{x[0][0]}</div><div><h3>{x[0]}</h3><p>{x[1]}</p></div><strong className="km">{x[2]}</strong></article>)}<div className="ready"><CheckCircle2/><div><strong>{t.found}</strong><p>{t.sub}</p></div></div></section><aside><div><span>{t.distance}</span><strong>15 км</strong></div><div><span>{t.people}</span><strong>3</strong></div><button className="primary"><Search size={18}/>{t.expand}</button></aside></div></div></main>}

function Profile({t}){const [saved,setSaved]=useState(false);const [error,setError]=useState("");const [f,setF]=useState({name:"",city:"",can_help:"",have:"",can_share:"",useful:"",needs:"",contact:""});const fields=[["name",t.name],["city",t.city],["can_help",t.can],["have",t.have],["can_share",t.share],["useful",t.useful],["needs",t.need],["contact",t.contact]];async function submit(e){e.preventDefault();setError("");if(supabase){const payload={slug:`${f.name.toLowerCase().replace(/[^a-zа-яіїє0-9]+/gi,"-")}-${Date.now().toString().slice(-5)}`,name:f.name,city:f.city,headline:f.useful||f.can_help||"Можливість",can_help:[f.can_help,f.have,f.useful].filter(Boolean).join(". "),can_share:f.can_share,needs:f.needs,contact:f.contact};const r=await supabase.from("profiles").insert(payload);if(r.error){setError(r.error.message);return}}setSaved(true)}return <main className="page"><section className="profileShell"><span className="kicker">ATLAS</span><h1>{t.profile}</h1><form className="profileForm" onSubmit={submit}>{fields.map(([n,l],i)=><label key={n}><span>{l}</span>{i<2||n==="contact"?<input required={n==="name"||n==="contact"} value={f[n]} onChange={e=>setF({...f,[n]:e.target.value})}/>:<textarea value={f[n]} onChange={e=>setF({...f,[n]:e.target.value})}/>}</label>)}{error&&<div className="error">{error}</div>}{saved&&<div className="success">{t.saved}</div>}<button className="primary">{t.save}</button></form></section></main>}

export default function App(){const [lang,setLang]=useState("uk");const t=useMemo(()=>dict[lang],[lang]);return <><Header lang={lang} setLang={setLang} t={t}/><Routes><Route path="/" element={<Home t={t}/>}/><Route path="/solution" element={<Solution t={t}/>}/><Route path="/profile" element={<Profile t={t}/>}/></Routes><footer>Atlas 2.0 Foundation</footer></>}
